
name: Build and Deploy to Azure

env:
  AZURE_CONTAINER_REGISTRY_NAME: "byd1371"
  AZURE_CONTAINER_REGISTRY: "byd1371.azurecr.io"
  CONTAINER_NAME: "frontend"
  RESOURCE_GROUP: "1"

on:
  push: 
    branches: [ "social-app" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildContainerImage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Set up Docker Builx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
           # Container registry username
           username: ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}
           # Container registry password
           password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
           # Container registry server url
           login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}

      - name: Build and push Frontend Docker images
        uses: docker/build-push-action@v6.9.0
        with:
           push: true
           tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
           file: ./client/Dockerfile

  Deploytoazurecontainerapp:
      runs-on: ubuntu-latest
      permissions:
        actions: read
        contents: read
        id-token: write
      environment: production
      needs: [buildContainerImage]
     
      
      steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: '429a9a2c-b403-4532-8822-93a7425d56f1'
          tenant-id: '522316bf-80fd-435f-97bc-f74fab0b6188'
          subscription-id: '0903c605-8b86-400b-9502-a2969a03e8d2'

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          resourceGroup: '1'
          containerAppName: "frontend"




        
