
name: Build and Deploy to Azure

env:
  AZURE_CONTAINER_REGISTRY_NAME: "BYD1371"
  AZURE_CONTAINER_REGISTRY: "byd1371.azurecr.io"
  CONTAINER_NAME: "frontend"
  RESOURCE_GROUP: "1"

on:
  push: 
    branches: [ "social-app" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildContainerImage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Set up Docker Builx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
           # Container registry username
           username: ${{ env.AZURE_CONTAINER_REGISTRY_NAME }}
           # Container registry password
           password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
           # Container registry server url
           login-server: ${{ env.AZURE_CONTAINER_REGISTRY }}

      - name: Build and push Frontend Docker images
        uses: docker/build-push-action@v6.9.0
        with:
           push: true
           tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
           file: ./client/Dockerfile

      - name: Build and push Backend Docker images
        uses: docker/build-push-action@v6.9.0
        with:
           push: true
           tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}
           file: ./api/Dockerfile

  Deploytoazurecontainerapp:

  
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
    
    needs: [buildContainerImage]
    steps:

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: '${{ env.AZURE_CONTAINER_REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}'
          resourceGroup: 'RESOURCE_GROUP'
          containerAppName: '${{ env.CONTAINER_NAME }}'

           
